apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-restore
  namespace: db
spec:
  template:
    spec:
      containers:
      - name: mysql-client
        image: rondochen/mysql-data:1.0
        command: 
          - bash
          - "-c"
          - |
            mysql -uroot -pP@ssword1234_ -hmysql-0.mysql --default-character-set=utf8mb4 < /data/dump.sql
      restartPolicy: Never
  backoffLimit: 2
  ttlSecondsAfterFinished: 100
