FROM maven:3.5-jdk-8-alpine as builder
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean package

FROM openjdk:8-jdk-alpine
RUN mkdir /app
COPY --from=builder /usr/src/app/target/product.jar /app
WORKDIR /app
EXPOSE 3000
# ENTRYPOINT ["java","-jar","product.jar"]
